name = "AbaqusUnitCell2D"
uuid = "aad359ed-a677-4ee1-8d11-07b4cf147889"
authors = ["Raphael <raphael.suda@gmx.net>"]
version = "0.1.0"

[deps]
StringArrayEditor = "9ac07dbc-a56c-11e8-2053-773943ca4811"
